DROP TABLE IF EXISTS result; 
CREATE EXTERNAL TABLE result(f1 INT, f2 INT, f3 INT, f4 INT) 
	ROW FORMAT DELIMITED 
	FIELDS TERMINATED BY ','
	LINES TERMINATED BY '\n' 
	STORED AS TEXTFILE
	LOCATION '${hiveconf:input}';

INSERT OVERWRITE LOCAL DIRECTORY '${hiveconf:output}' 
	SELECT f4 FROM result;